name: 測試 Actions 最大執行時間

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 持續執行
        run: |
          node -e "
          const start = Date.now();

          console.log('開始:', new Date(start).toISOString());

          setInterval(() => {
              const elapsed = Date.now() - start;

              const seconds = Math.floor(elapsed / 1000);
              const h = Math.floor(seconds / 3600);
              const m = Math.floor((seconds % 3600) / 60);
              const s = seconds % 60;

              console.log(
                  '已執行:',
                  h + ' 小時',
                  m + ' 分',
                  s + ' 秒'
              );
          }, 60000);
          "